export const Langs = new Map<string, string>([
    ["Spanish", "es"],
    ["English", "en"],
    ["French", "fr"],
    ["German", "de"],
    ["Italian", "it"],
    ["Portuguese", "pt"],
    ["Russian", "ru"],
    ["Japanese", "ja"],
    ["Chinese (Mandarin)", "zh"],
    ["Arabic", "ar"],
    ["Korean", "ko"],
    ["Swedish", "sv"],
    ["Dutch", "nl"],
    ["Polish", "pl"],
    ["Hungarian", "hu"],
    ["Greek", "el"],
    ["Vietnamese", "vi"],
    ["Thai", "th"],
    ["Indonesian", "id"],
    ["Bengali", "bn"],
    ["Turkish", "tr"],
    ["Swahili", "sw"],
    ["Yoruba", "yo"],
    ["Zulu", "zu"],
    ["Amharic", "am"],
    ["Nahuatl", "nah"],
    ["Quechua", "qu"],
    ["Maya", "myn"],
    ["Hindi", "hi"],
    ["Persian", "fa"],
    ["Hebrew", "he"],
    ["Ukrainian", "uk"],
    ["Czech", "cs"]
]);
